<?php

namespace App\Models;

use App\Models\Lesson;
use App\Models\Traits\Common;
use App\Observers\VideoObserver;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;

class Video extends Model
{
    use SoftDeletes, Common,Searchable;
    protected $fillable = ['title', 'path'];
    protected $dates = ['deleted_at'];

    protected static function boot()
    {
        self::observe(VideoObserver::class);
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function lesson()
    {
        return $this->belongsTo(Lesson::class);
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function getLink($param)
    {
        return route('edu.video.show', $this) . $param;
    }

}
